// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreSystem.Database;

public partial class Order
{
    public long OrderId { get; set; }

    public string OrderMember { get; set; }

    public string OrderStatus { get; set; }

    public DateTime? OrderDate { get; set; }

    public string ReceiveMember { get; set; }

    public string ReceivePhone { get; set; }

    public string ReceiveAddress { get; set; }

    public string PayMethod { get; set; }

    public string PayStatus { get; set; }

    public string ShippingMethod { get; set; }

    public string ShippingStatus { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    public virtual ICollection<OrderProduct> OrderProducts { get; set; } = new List<OrderProduct>();
}