// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreSystem.Database;

public partial class ProductStock
{
    public long ProductStockId { get; set; }

    public long? ProductId { get; set; }

    public int? Quantity { get; set; }

    public int? WarehouseId { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    public virtual Product Product { get; set; }
}