// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreSystem.Database;

public partial class ProductFile
{
    public long ProductFileId { get; set; }

    public long ProductId { get; set; }

    public string FileName { get; set; }

    public string Path { get; set; }

    public int? Sort { get; set; }

    public DateTime? CreateTime { get; set; }

    public virtual Product Product { get; set; }
}