// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreSystem.Database;

public partial class ProductPrice
{
    public long ProductCurrentPriceId { get; set; }

    public long ProductId { get; set; }

    public decimal? Price { get; set; }

    public string Currency { get; set; }

    public DateTime? EffectiveStartTime { get; set; }

    public DateTime? EffectiveEndTime { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    public virtual Product Product { get; set; }
}