// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreSystem.Database;

public partial class SYS_User
{
    public string UserId { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }
}